version: "3.6"
services:
  citrusdb:
    container_name: citrusdb
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.citrus:/var/lib/postgresql/data
      - ./db.init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=citrus
      - POSTGRES_PASSWORD=citrus
      - TIMESCALEDB_TELEMETRY=off
    restart: "on-failure"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
